### ISSUE TITLE
make std_spec bug

### ISSUE THREAD

**Issue by femto** [crystal-lang/crystal#14200]
## Bug Report
now it comes to 
```
...................*.........Unhandled exception in spawn: SSL_read: I/O error (OpenSSL::SSL::Error)
  from src/openssl/ssl/socket.cr:137:9 in 'unbuffered_read'
  from src/io/buffered.cr:263:5 in 'fill_buffer'
  from src/io/buffered.cr:105:7 in 'peek'
  from src/http/request.cr:180:15 in 'parse_request_line'
  from src/http/request.cr:153:12 in 'from_io:max_request_line_size:max_headers_size'
  from src/http/server/request_processor.cr:30:19 in 'process'
  from src/http/server.cr:521:5 in 'handle_client'
  from src/http/server.cr:451:5 in '->'
  from src/fiber.cr:146:11 in 'run'
  from src/fiber.cr:98:34 in '->'
Caused by: SSL_read: No such file or directory (RuntimeError)

```

**Comment by Blacksmoke16** [comment]
Did you try on the latest commit in master? Would have thought this would have been fixed by https://github.com/crystal-lang/crystal/pull/14169 given it's the same error message.

**Comment by femto** [comment]
my commit is
0b57b6cc8 (HEAD -> master, github/master) Add `Signal::trap_handler?` (#14126)

**Comment by femto** [comment]
```
Unhandled exception in spawn: SSL_read: I/O error (OpenSSL::SSL::Error)
  from src/openssl/ssl/socket.cr:137:9 in 'unbuffered_read'
  from src/io/buffered.cr:263:5 in 'fill_buffer'
  from src/io/buffered.cr:105:7 in 'peek'
  from src/http/request.cr:180:15 in 'parse_request_line'
  from src/http/request.cr:153:12 in 'from_io:max_request_line_size:max_headers_size'
  from src/http/server/request_processor.cr:30:19 in 'process'
  from src/http/server.cr:521:5 in 'handle_client'
  from src/http/server.cr:451:5 in '->'
  from src/fiber.cr:146:11 in 'run'
  from src/fiber.cr:98:34 in '->'
Caused by: SSL_read: No such file or directory (RuntimeError)
..................................................................................................................................................................................................................................................................................................................................................................................................................*................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Pending:
  String #reverse converts invalid code units to replacement char
  Regex #matches_at_byte_index? negative
  Regex #match with pos negative
  Regex #match_at_byte_index negative
  Spec matchers pending block is not compiled pending has block with valid syntax, but invalid semantics
  String#each_grapheme GB9c
  String#each_grapheme GB9c
  String#each_grapheme GB9c
  String#each_grapheme GB9c
  String#each_grapheme GB9c
  String#each_grapheme GB9c
  String#each_grapheme GB9c
  URI .parse unescaped @ in user/password should not confuse host
  Number #round edge cases
  UDPSocket using IPv6 joins and transmits to multicast groups
  UDPSocket sends broadcast message
  UDPSocket #connect with a IPv6 address
  concurrent schedules intermitting sleeps
  Math Functions for computing quotient and remainder
  OpenSSL::X509::Certificate #digest
  OpenSSL::SSL::Context ciphers uses intermediate default ciphers
  Path #expand converts a pathname to an absolute pathname, using a complete path assert

Finished in 2:25 minutes
17646 examples, 0 failures, 0 errors, 22 pending
```
the error output in the middle,
but it says 0 failures

**Comment by femto** [comment]
now it becomes
```
Unhandled exception in spawn: SSL_read: I/O error (OpenSSL::SSL::Error)
  from src/openssl/ssl/socket.cr:137:9 in 'unbuffered_read'
  from src/io/buffered.cr:263:5 in 'fill_buffer'
  from src/io/buffered.cr:105:7 in 'peek'
  from src/http/request.cr:180:15 in 'parse_request_line'
  from src/http/request.cr:153:12 in 'from_io:max_request_line_size:max_headers_size'
  from src/http/server/request_processor.cr:30:19 in 'process'
  from src/http/server.cr:521:5 in 'handle_client'
  from src/http/server.cr:451:5 in '->'
  from src/fiber.cr:146:11 in 'run'
  from src/fiber.cr:98:34 in '->'
Caused by: SSL_read: No child processes (RuntimeError)

```

**Comment by straight-shoota** [comment]
Looks like https://github.com/crystal-lang/crystal/pull/14169 didn't really resolve this then. I wasn't too sure it would actually work 🤷

**Comment by straight-shoota** [comment]
I'm declaring this as a (potential) regression because it appears as if https://github.com/crystal-lang/crystal/pull/14169 might've degraded stability on previously sound workloads.

**Comment by straight-shoota** [comment]
Resolved by #14217
