### ISSUE TITLE
CRYSTAL_BIO error when requiring third-party lib

### ISSUE THREAD

**Issue by plukevdh** [crystal-lang/crystal#2515]
Pulled in [Crustache](https://github.com/MakeNowJust/crustache) last week into a project doing simple template rendering and running specs works perfectly fine, but attempting to build the project, I get the following error:

```
crystal build src/biplane.cr
Error in /usr/local/Cellar/crystal-lang/0.15.0/src/openssl/bio.cr:11: instantiating 'IO#write(Slice(UInt8))'

      io.write Slice.new(data, len)
         ^~~~~

in /usr/local/Cellar/crystal-lang/0.15.0/src/openssl/bio.cr:5: constant OpenSSL::BIO::CRYSTAL_BIO requires initialization of Crustache::Parser::NEWLINE_N, which is initialized later. Initialize Crustache::Parser::NEWLINE_N before OpenSSL::BIO::CRYSTAL_BIO

  CRYSTAL_BIO = begin
  ^~~~~~~~~~~

make: *** [build] Error 1
```

Not sure why a stdlib is complaining about a constant defined in a third-party lib here. That's also the full extent of the stack trace so I'm not really sure how to track down further info about where this is occurring. Let me know what I can do to help figure this one out.

**Comment by plukevdh** [comment]
Hmm, on a whim, I moved around some `require` statements for crustache much farther up the chain and the issue went away. Still would love to see this one solved or at least commented on as to why.

**Comment by MakeNowJust** [comment]
@plukevdh I'm creator of crustache. Thanks for using it. Hmm, that's strange and interesting. Then, I tried below code and got a following error.

```crystal
require "../src/crustache"
require "openssl"

p OpenSSL::BIO::CRYSTAL_BIO
```

```
Error in /usr/lib/crystal/openssl/bio.cr:9: expected block to return Int32, not NoReturn

    crystal_bio.bwrite = LibCrypto::BioMethodWrite.new do |bio, data, len|
                         ^
```

So, I guess, this error was caused by `Crustache::IndentIO#write` method and that Crystal's type inference rule was changed. However, I can't find problem in my code. What do you think, @asterite ?

**Comment by MakeNowJust** [comment]
`Crustache::IndentIO#write` was inferred as `NoReturn`..?

**Comment by asterite** [comment]
It happens also with this:

```crystal
require "openssl"

OpenSSL::BIO::CRYSTAL_BIO
```

**Comment by MakeNowJust** [comment]
Oh, thanks!  月曜日, 25 4月 2016, 11:52午後 +09:00 from Ary Borenszweig < notifications@github.com> :

**Comment by asterite** [comment]
Reduced to:

```crystal
lib LibFoo
  struct Some
    x : ->
  end
end

X = LibFoo::Some.new
p X
```

**Comment by plukevdh** [comment]
❤️  thanks for quick work on this!

**Comment by asterite** [comment]
@plukevdh Note that the original error seems to be unrelated to the problem I fixed. If you could share a snippet of code (or instructions) that reproduce the "constant ... requires initialization of ..." problem, that would be great.

**Comment by plukevdh** [comment]
Will investigate and report back if I can create a reduced reproducible example.

**Comment by plukevdh** [comment]
Haven't managed a scaled down version, but I can give you a branch with the code that causes a compilation error: https://github.com/articulate/biplane/tree/env-interpolation

**Comment by plukevdh** [comment]
Oddly enough, that branch builds successfully on CI (Travis) but still fails locally. So it may be something getting cached locally between builds?
